name: flutter_challenge_gryffindor_fase_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  # External packages
  melos: ^5.3.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Local packages
  commons:
    path: packages/commons
  commons_ui:
    path: packages/commons_ui

  modular_router:
   git: 
    url: https://github.com/andresduke024/modular_router.git
    ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/config/
    - assets/images/